### ISSUE TITLE
OSError after install

### ISSUE THREAD

**Issue by arthus701** [dolgov/TT-IRT#1]
When following the install directions, I got the following ``OSError``:

> OSError: ~/.local/lib/python3.7/site-packages/tt_irt1.so: cannot open shared object file: No such file or directory

I found the ``.so`` file under the name ``tt_irt1.cpython-37m-x86_64-linux-gnu.so`` and removing the middle part did the job, but I'm not sure if this is intended behaviour...

**Comment by dolgov** [comment]
Hello,
this is definitely not an intended behaviour, thanks for working out these nasty Python compatibility issues for me. I have committed a glob package way of locating libraries, this should hopefully work.

**Comment by arthus701** [comment]
The new version worked for me, thanks for the quick fix.
